@startuml
skinparam DefaultFontName HG行書体
scale 1.5
left to right direction
actor 購入者
note bottom of 購入者
	会員登録済み
end note
actor 販売者
rectangle ショッピングサイト{
	購入者 --> (検索する)
	購入者 --> (商品詳細を見る)
	購入者 --> (カートに入れる)
	購入者 --> (カートから削除)
	購入者 --> (注文する)
	(注文を見る) <-- 販売者
	(商品を登録する) <-- 販売者
	(商品を編集する) <-- 販売者
	(在庫を入力する) <-- 販売者
	(購入者にメールを送る) <-- 販売者
}
@enduml